"""add user_id to boleto validations

Revision ID: a035e05beb95
Revises: 2fbe687a0578
Create Date: 2026-05-08 09:20:56.362208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a035e05beb95'
down_revision: Union[str, None] = '2fbe687a0578'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boleto_validations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('code', sa.String(length=44), nullable=False),
    sa.Column('original_code', sa.String(length=48), nullable=False),
    sa.Column('boleto_type', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('due_date_factor', sa.String(length=4), nullable=True),
    sa.Column('is_expired', sa.Boolean(), nullable=False),
    sa.Column('days_overdue', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('reasons', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_boleto_validations_code'), 'boleto_validations', ['code'], unique=False)
    op.create_index(op.f('ix_boleto_validations_status'), 'boleto_validations', ['status'], unique=False)
    op.create_index(op.f('ix_boleto_validations_user_id'), 'boleto_validations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_boleto_validations_user_id'), table_name='boleto_validations')
    op.drop_index(op.f('ix_boleto_validations_status'), table_name='boleto_validations')
    op.drop_index(op.f('ix_boleto_validations_code'), table_name='boleto_validations')
    op.drop_table('boleto_validations')
    # ### end Alembic commands ###
