"""initial schema

Revision ID: 55f44253fe9e
Revises: 
Create Date: 2026-04-24 09:04:59.845343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '55f44253fe9e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link_analyses',
    sa.Column('url', sa.String(length=2083), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('risk', sa.String(length=10), nullable=False),
    sa.Column('reasons', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('url', 'user_id')
    )
    op.create_index(op.f('ix_link_analyses_url'), 'link_analyses', ['url'], unique=False)
    op.create_index(op.f('ix_link_analyses_user_id'), 'link_analyses', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_link_analyses_user_id'), table_name='link_analyses')
    op.drop_index(op.f('ix_link_analyses_url'), table_name='link_analyses')
    op.drop_table('link_analyses')
    # ### end Alembic commands ###
