"""remove boleto validation table

Revision ID: e53ffb066b29
Revises: 1098becfc3b7
Create Date: 2026-05-11 11:30:38.974213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e53ffb066b29'
down_revision: Union[str, None] = '1098becfc3b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_boleto_validations_code', table_name='boleto_validations')
    op.drop_index('ix_boleto_validations_status', table_name='boleto_validations')
    op.drop_index('ix_boleto_validations_user_id', table_name='boleto_validations')
    op.drop_table('boleto_validations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boleto_validations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=44), autoincrement=False, nullable=True),
    sa.Column('original_code', sa.VARCHAR(length=48), autoincrement=False, nullable=False),
    sa.Column('boleto_type', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('due_date_factor', sa.VARCHAR(length=4), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('reasons', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_real', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('risk_score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('positives', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='boleto_validations_pkey')
    )
    op.create_index('ix_boleto_validations_user_id', 'boleto_validations', ['user_id'], unique=False)
    op.create_index('ix_boleto_validations_status', 'boleto_validations', ['status'], unique=False)
    op.create_index('ix_boleto_validations_code', 'boleto_validations', ['code'], unique=False)
    # ### end Alembic commands ###
