"""refactor link_analysis primary key

Revision ID: 26b5a3961ca6
Revises: 55f44253fe9e
Create Date: 2026-04-24 09:30:19.588733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26b5a3961ca6'
down_revision: Union[str, None] = '55f44253fe9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link_analyses', sa.Column('id', sa.UUID(), nullable=False))
    op.add_column('link_analyses', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index('ix_link_analyses_url', table_name='link_analyses')
    op.create_unique_constraint('uq_user_url', 'link_analyses', ['url', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_url', 'link_analyses', type_='unique')
    op.create_index('ix_link_analyses_url', 'link_analyses', ['url'], unique=False)
    op.drop_column('link_analyses', 'updated_at')
    op.drop_column('link_analyses', 'id')
    # ### end Alembic commands ###
