"""update boleto_validation model

Revision ID: 1098becfc3b7
Revises: a035e05beb95
Create Date: 2026-05-08 11:02:01.836115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1098becfc3b7'
down_revision: Union[str, None] = 'a035e05beb95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boleto_validations', sa.Column('is_real', sa.Boolean(), nullable=False))
    op.add_column('boleto_validations', sa.Column('risk_score', sa.Integer(), nullable=False))
    op.add_column('boleto_validations', sa.Column('positives', postgresql.ARRAY(sa.Text()), nullable=False))
    op.alter_column('boleto_validations', 'code',
               existing_type=sa.VARCHAR(length=44),
               nullable=True)
    op.alter_column('boleto_validations', 'amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('boleto_validations', 'status',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.drop_column('boleto_validations', 'days_overdue')
    op.drop_column('boleto_validations', 'is_expired')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boleto_validations', sa.Column('is_expired', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('boleto_validations', sa.Column('days_overdue', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('boleto_validations', 'status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)
    op.alter_column('boleto_validations', 'amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('boleto_validations', 'code',
               existing_type=sa.VARCHAR(length=44),
               nullable=False)
    op.drop_column('boleto_validations', 'positives')
    op.drop_column('boleto_validations', 'risk_score')
    op.drop_column('boleto_validations', 'is_real')
    # ### end Alembic commands ###
