"""recreate link_analyses with id pk

Revision ID: 2fbe687a0578
Revises: 26b5a3961ca6
Create Date: 2026-04-24 09:33:13.941940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2fbe687a0578'
down_revision: Union[str, None] = '26b5a3961ca6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link_analyses',
    sa.Column('url', sa.String(length=2083), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('risk', sa.String(length=10), nullable=False),
    sa.Column('reasons', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url', 'user_id', name='uq_user_url')
    )
    op.create_index(op.f('ix_link_analyses_user_id'), 'link_analyses', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_link_analyses_user_id'), table_name='link_analyses')
    op.drop_table('link_analyses')
    # ### end Alembic commands ###
